name: Sync to Gitee

on:
  push:
    branches:
      - main  # 或者 master，取决于您的主分支名称
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:${{ github.repository }}.git
          destination-repo: git@gitee.com:${{ secrets.GITEE_USERNAME }}/${{ secrets.GITEE_REPO }}.git 